export const IMFSRoutes = {
    Login: 'login',
    Home: 'home',
    QuoteRates: 'quote-rate',
    QuoteBreakTotalRates: 'quote-break-total-rate',
    QuoteBreakPercentRates: 'quote-break-percent-rate',
    Funders: 'funder',
    Vendors: 'vendor',
    FinanceTypes: 'finance-type',
    FinanceProductTypes: 'finance-product-type',
    Quote: 'quote/quote-details',
    QuoteSearch: 'quote/quote-search',
    QuoteEmail: 'quote/quote-email',
    QuoteAcceptance: 'quote/quote-acceptance',
    Menu: 'menu',
    Email: 'email/write-email',
    User: 'user-list',
    Application: 'application/application-details',
    ApplicationSearch: 'application/application-search',
};
